---
title: "R Notebook"
output: html_notebook
---

```{r}
library(scater)
library(scran)
library(ggplot2)
library(cluster)

```

```{r}
load("SCE_NN79.RData")
sce79.4_qc$group <- paste(sce79.4_qc$H1975, sce79.4_qc$H2228, sce79.4_qc$HCC827, sep = "-")
col <- rgb(sce79.4_qc$H1975, sce79.4_qc$H2228, sce79.4_qc$HCC827, maxColorValue = 9)
```

## functions

```{r}
cor_9cell_within <- function(sce, norm_assay = "norm_exprs") {
  cor_val = c()
  cell = c()
  norm_mat = assay(sce, norm_assay)
  for(group in unique(sce$group)){
    sel_cell = colData(sce)$group == group
    cor_mat = cor(norm_mat[,sel_cell])
    cor_mat[!lower.tri(cor_mat)] = NA
    cor_mat = as.numeric(cor_mat)
    cor_mat = cor_mat[!is.na(cor_mat)]
    cor_val = c(cor_val, cor_mat)
    cell = c(cell, rep(group, length(cor_mat)))
  }
  res_df = data.frame(cor_val = cor_val, group = cell)
}
```

```{r}
# require the SCE to be the result of dimension reduction
# this function calculates the true distance of the k cells that is closest in the dimension reduction result where k is the number of cell within  group
cal_knn_avg_distance <- function(SCE){
  cell_annotation = data.frame(colData(SCE))
  cell_matrix <- as.matrix(cell_annotation[,c("H1975", "H2228", "HCC827")])
  true_distance_matrix = as.matrix(dist(cell_matrix, method = "euclidean"))
  rd_distance_matrix = as.matrix(dist(reducedDim(SCE)))
  
  avg_distance = c()
  grp = table(colData(SCE)$group)
  for(i in 1:ncol(SCE)){
    knn = order(rd_distance_matrix[rownames(cell_annotation)[i],])[1:(grp[cell_annotation$group[i]])]
    avg_distance = c(avg_distance, sum(true_distance_matrix[rownames(cell_annotation)[i], knn])/grp[cell_annotation$group[i]])
  }
  names(avg_distance) = rownames(cell_annotation)
  return(avg_distance)
}
  
```


```{r}
calcSilhouette <- function(SCE, name){
  sil <- silhouette(as.numeric(factor(SCE$group)), dist(reducedDim(SCE)))
  sil <- data.frame(sil[1:nrow(sil),])
  method <- rep(name, nrow(sil))
  sil <- cbind(sil, method)
}
```

#Analysis

## raw count PCA
```{r}
time_raw <- system.time({
logcounts(sce79.4_qc) <- log2(counts(sce79.4_qc) + 1)
})
PCA_raw <- runPCA(sce79.4_qc, exprs_values = "logcounts")
p0 <- plotPCASCE(PCA_raw, colour_by = "group")+ ggtitle("log raw counts")+ scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group)) + theme(legend.position="none")

sil0 <- calcSilhouette(PCA_raw, "raw count")
# cor_df_raw <- cor_9cell_within(sce79.4_qc, "logcounts")
```


## kNN

```{r}
source("/wehisan/home/allstaff/d/dong.x/mixture/knn-smoothing-master/knn_smooth.R")
# source("/Volumes/dong.x-2/mixture/knn-smoothing-master/knn_smooth.R")
time_knn1 <- system.time({
sce79.4_smoothed = knn_smoother(counts(sce79.4_qc), k = 1)
assay(sce79.4_qc, "knn1") = log2(sce79.4_smoothed + 1)
})
time_knn3 <- system.time({
sce79.4_smoothed = knn_smoother(counts(sce79.4_qc), k = 3)
assay(sce79.4_qc, "knn3") = log2(sce79.4_smoothed + 1)
})
time_knn7 <- system.time({
sce79.4_smoothed = knn_smoother(counts(sce79.4_qc), k = 7)
assay(sce79.4_qc, "knn7") = log2(sce79.4_smoothed + 1)
})
time_knn15 <- system.time({
sce79.4_smoothed = knn_smoother(counts(sce79.4_qc), k = 15)
assay(sce79.4_qc, "knn15") = log2(sce79.4_smoothed + 1)
})
time_knn31 <- system.time({
sce79.4_smoothed = knn_smoother(counts(sce79.4_qc), k = 31)
assay(sce79.4_qc, "knn31") = log2(sce79.4_smoothed + 1)
})
time_knn63 <- system.time({
sce79.4_smoothed = knn_smoother(counts(sce79.4_qc), k = 63)
assay(sce79.4_qc, "knn63") = log2(sce79.4_smoothed + 1)
})
time_knn127 <- system.time({
sce79.4_smoothed = knn_smoother(counts(sce79.4_qc), k = 127)
assay(sce79.4_qc, "knn127") = log2(sce79.4_smoothed + 1)
})
time_knn255 <- system.time({
sce79.4_smoothed = knn_smoother(counts(sce79.4_qc), k = 255)
assay(sce79.4_qc, "knn255") = log2(sce79.4_smoothed + 1)
})

k1 <- runPCA(sce79.4_qc, exprs_values = "knn1")
k3 <- runPCA(sce79.4_qc, exprs_values = "knn3")
k7 <- runPCA(sce79.4_qc, exprs_values = "knn7")
k15 <- runPCA(sce79.4_qc, exprs_values = "knn15")
k31 <- runPCA(sce79.4_qc, exprs_values = "knn31")
k63 <- runPCA(sce79.4_qc, exprs_values = "knn63")
k127 <- runPCA(sce79.4_qc, exprs_values = "knn127")
k255 <- runPCA(sce79.4_qc, exprs_values = "knn255")

PCAk1 <- plotPCASCE(k1, colour_by = "group", exprs_values = "knn1", ncomponents = 2) + ggtitle("k = 1")+ theme(legend.position="none") + scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group))
PCAk3 <- plotPCASCE(k3, colour_by = "group", exprs_values = "knn3", ncomponents = 2) + ggtitle("k = 3")+ theme(legend.position="none") + scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group))
PCAk7 <- plotPCASCE(k7, colour_by = "group", exprs_values = "knn7", ncomponents = 2) + ggtitle("k = 7")+ theme(legend.position="none") + scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group))
PCAk15 <- plotPCASCE(k15, colour_by = "group", exprs_values = "knn15", ncomponents = 2) + ggtitle("k = 15")+ theme(legend.position="none") + scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group))
PCAk31 <- plotPCASCE(k31, colour_by = "group", exprs_values = "knn31", ncomponents = 2) + ggtitle("k = 31")+ theme(legend.position="none") + scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group))
PCAk63 <- plotPCASCE(k63, colour_by = "group", exprs_values = "knn63", ncomponents = 2) + ggtitle("k = 63")+ theme(legend.position="none") + scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group))
PCAk127 <- plotPCASCE(k127, colour_by = "group", exprs_values = "knn127", ncomponents = 2) + ggtitle("k = 127")+ theme(legend.position="none") + scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group))
PCAk255 <- plotPCASCE(k255, colour_by = "group", exprs_values = "knn255", ncomponents = 2) + ggtitle("k = 255")+ theme(legend.position="none") + scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group))
save(PCAk1, PCAk3, PCAk7, PCAk15, PCAk31, PCAk63, PCAk127, PCAk255, file = "pca_knn_9cells.RData")
multiplot(PCAk1, PCAk3, PCAk7, PCAk15, PCAk31, PCAk63, PCAk127, PCAk255, cols=3)

 sil_knn <- calcSilhouette(k15, "kNN (k=15)")

# cor_df_knn <- cor_9cell_within(sce79.4_qc, "knn")
```

## scran

```{r}
time_scran <- system.time({
sce79.4_qc <- computeSumFactors(sce79.4_qc)
sce79.4_qc <- normalize(sce79.4_qc)
assay(sce79.4_qc, "scran") <- logcounts(sce79.4_qc)
})
PCA_scran <- runPCA(sce79.4_qc, exprs_values = "scran")

p1 <- plotPCASCE(PCA_scran, colour_by = "group")+ ggtitle("scran")+ scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group)) + theme(legend.position="none")

sil1 <- calcSilhouette(PCA_scran, "scran")

cor_df_scran <- cor_9cell_within(sce79.4_qc, "scran")
```

## BASiCS

```{r}
library(BASiCS)

  sce79.4_qc_B <- sce79.4_qc[!grepl("^Gm", rownames(sce79.4_qc)),]
  sce79.4_qc_B <- sce79.4_qc_B[!grepl("^Rpl", rownames(sce79.4_qc_B)),]
  sce79.4_qc_B <- sce79.4_qc_B[!grepl("^Rps", rownames(sce79.4_qc_B)),]
  sce79.4_qc_B <- sce79.4_qc_B[!grepl("^mt-", rownames(sce79.4_qc_B)),]
  sce79.4_qc_B <- sce79.4_qc_B[order(isSpike(sce79.4_qc_B)),]
  # sce79.4_qc_B <- sce79.4_qc_B[!grepl("^ERCC", rownames(sce79.4_qc_B)),]
  sce79.4_qc_B$group <- paste(sce79.4_qc_B$H1975, sce79.4_qc_B$H2228, sce79.4_qc_B$HCC827, sep = "_")
  
  cms_095046 <- read.delim("cms_095046.txt", stringsAsFactors = FALSE)
  
  SpikeInfo = data.frame(ERCCID=cms_095046$ERCC.ID, count=cms_095046$concentration.in.Mix.1..attomoles.ul.)
  SpikeInfo = SpikeInfo[SpikeInfo$ERCCID %in% rownames(sce79.4_qc_B)[isSpike(sce79.4_qc_B)],]
  rownames(SpikeInfo) = SpikeInfo$ERCCID
  SpikeInfo[,2] = SpikeInfo[,2]/1000
  metadata(sce79.4_qc_B) <- list(SpikeInput = SpikeInfo[rownames(sce79.4_qc_B)[isSpike(sce79.4_qc_B)],2],BatchInfo = colData(sce79.4_qc_B)$group)
  
time_BASiCS <- system.time({ 
  chain <- BASiCS_MCMC(sce79.4_qc_B, N = 10000, Thin = 10, Burn = 500, PrintProgress = TRUE, StoreChain = TRUE, StoreDir = "/wehisan/home/allstaff/d/dong.x/mixture/chain", RunName = "9_cell_mix_2")
  DenoisedCounts <- BASiCS_DenoisedCounts(Data = sce79.4_qc, Chain = chain)
  assay(sce79.4_qc, "log2_BASiCS") = log2(DenoisedCounts[match(rownames(sce79.4_qc), rownames(sce79.4_qc_B)),] + 1)
})
save(chain, time_BASiCS, sce79.4_qc_B,  file = "benchmark_9cell.4_BASiCS.RData")
rm(sce79.4_qc_B)

PCA_BASiCS <- runPCA(sce79.4_qc, exprs_values = "log2_BASiCS")
p3 <- plotPCASCE(PCA_BASiCS, colour_by = "group")+ ggtitle("BASiCS")+ scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group)) + theme(legend.position="none")

sil3 <- calcSilhouette(PCA_BASiCS, "BASiCS")
# cor_df_ra <- cor_9cell_within(sce79.4_qc, "logcounts")
```


## scran + DrImpute

```{r}
library(DrImpute)
time_DrImpute <- system.time({
imp <- DrImpute(assay(sce79.4_qc, "scran"))
assay(sce79.4_qc, "scran_DrImpute") <- imp
})
PCA_DrImpute <- runPCA(sce79.4_qc, exprs_values = "scran_DrImpute")
p2 <- plotPCASCE(PCA_DrImpute, colour_by = "group")+ ggtitle("scran+DrImpute")+ scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group)) + theme(legend.position="none")
sil2 <- calcSilhouette(PCA_DrImpute, "scran+DrImpute")

# cor_df_DrImpute <- cor_9cell_within(sce79.4_qc, "scran_DrImpute")
```

## Linnorm

```{r}
library(Linnorm)
time_Linnorm <- system.time({
linnorm_normalized <- Linnorm(counts(sce79.4_qc))
assay(sce79.4_qc, "linnorm") <- linnorm_normalized
})
PCA_linnorm <- runPCA(sce79.4_qc, exprs_values = "linnorm")
p4 <- plotPCASCE(PCA_linnorm, colour_by = "group")+ ggtitle("Linnorm")+ scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group)) + theme(legend.position="none")
sil4 <- calcSilhouette(PCA_linnorm, "Linnorm")

cor_df_linnorm <- cor_9cell_within(sce79.4_qc, "linnorm")
detach("package:Linnorm", unload=TRUE)
```

## DESeq

```{r}
library(DESeq)
time_DESeq <- system.time({
sizeFactors(sce79.4_qc) <- estimateSizeFactorsForMatrix(counts(sce79.4_qc))
sce79.4_qc <- normalize(sce79.4_qc)
assay(sce79.4_qc, "DESeq") <- logcounts(sce79.4_qc)
})
PCA_DESeq <- runPCA(sce79.4_qc, exprs_values = "DESeq")
p5 <- plotPCASCE(PCA_DESeq, colour_by = "group")+ ggtitle("DESeq")+ scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group)) + theme(legend.position="none")
sil5 <- calcSilhouette(PCA_DESeq, "DESeq")
# cor_df_DESeq <- cor_9cell_within(sce79.4_qc, "DESeq")
```

## TMM

```{r}
library(edgeR)
time_TMM <- system.time({
sizeFactors(sce79.4_qc) <- calcNormFactors(counts(sce79.4_qc), method = "TMM")
sce79.4_qc <- normalize(sce79.4_qc)
assay(sce79.4_qc, "TMM") <- logcounts(sce79.4_qc)
})
PCA_TMM <- runPCA(sce79.4_qc, exprs_values = "TMM")
p8 <- plotPCASCE(PCA_TMM, colour_by = "group")+ ggtitle("TMM")+ scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group)) + theme(legend.position="none")
sil8 <- calcSilhouette(PCA_TMM, "TMM")
# cor_df_TMM <- cor_9cell_within(sce79.4_qc, "TMM")
```

## CPM
```{r}
time_CPM <- system.time(
assay(sce79.4_qc, "CPM") <- log2(edgeR::cpm(counts(sce79.4_qc)) + 1)
)
library(DrImpute)
assay(sce79.4_qc, "CPM_DrImpute") <- DrImpute(assay(sce79.4_qc, "CPM"))
PCA_CPM <- runPCA(sce79.4_qc, exprs_values = "CPM")
p6 <- plotPCASCE(PCA_CPM, colour_by = "group")+ ggtitle("CPM")+ scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group)) + theme(legend.position="none")
PCA_CPM_DrImpute <- runPCA(sce79.4_qc, exprs_values = "CPM_DrImpute")
sil6 <- calcSilhouette(PCA_CPM, "CPM")
p7 <- plotPCASCE(PCA_CPM_DrImpute, colour_by = "group")+ ggtitle("CPM_DrImpute")+ scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group)) + theme(legend.position="none")
sil7 <- calcSilhouette(PCA_CPM_DrImpute, "CPM_DrImpute")
```

## SCnorm

```{r}
library(SCnorm)
#time1 <- Sys.time()
time_SCnorm <- system.time({
  SCnorm_out <- SCnorm(Data = counts(sce79.4_qc), Conditions = as.numeric(factor(sce79.4_qc$group)), PrintProgressPlots = T)
  assay(sce79.4_qc, "SCnorm") = log2(metadata(SCnorm_out)$NormalizedData + 1)
})
save(SCnorm_out, file = "SCnorm_out_new4.RData")
detach("package:SCnorm", unload=TRUE) 
```

<!-- 
Setting up parallel computation using 63 cores
At least one cell/sample has less than 10,000 counts total. 
       Check the quality of your data or filtering criteria. 
       SCnorm may not be appropriate for your data (see vignette for details).Gene filter is applied within each condition.
Error in SCnorm(Data = counts(sce79.4_qc), Conditions = as.numeric(factor(sce79.4_qc$group)), : At least one condition has less then 100 genes that pass the specified filter. Check the quality of your data or filtering criteria. SCnorm may not be appropriate for your data (see vignette for details).
Timing stopped at: 38.4 0.438 38.82
-->

## scone

```{r}
library(scone)

expr <- counts(sce79.4_qc)
bio <- factor(sce79.4_qc$group)


#Read in housekeeping gene list and convert gene symbol to ensembl gene ID using biomaRt.


hkgene <- read.csv("h-scHKgenes.csv", stringsAsFactors = FALSE, col.names = 1)
library(biomaRt)
ensembl = useMart("ensembl")
ensembl = useDataset("hsapiens_gene_ensembl", mart = ensembl)
hk <- getBM(attributes = c("ensembl_gene_id", "hgnc_symbol"), filters = "hgnc_symbol", mart = ensembl, values = hkgene$X1)


#Use housekeeping genes as negetive control
#time1 <- Sys.time()
time_scone <- system.time({
  negcon <- intersect(rownames(expr), hk$ensembl_gene_id)
  # creating a SconeExperiment Object
  my_scone <- SconeExperiment(expr, bio = bio, negcon_ruv = rownames(expr) %in% negcon)
  
  scaling=list(none=identity, # Identity - do nothing
               
               # eff = EFF_FN, # User-defined function
               
               sum = SUM_FN, # SCONE library wrappers...
               tmm = TMM_FN, 
               uq = UQ_FN,
               fq = FQT_FN,
               deseq = DESEQ_FN)
  
  BiocParallel::register(
    BiocParallel::SerialParam()
  ) # Register BiocParallel Serial Execution
  
  my_scone <- scone(my_scone,
                    #imputation = imputation, impute_args = impute_args,
                    scaling=scaling,
                    run=TRUE,
                    eval_kclust = NULL,stratified_pam = TRUE,
                    k_qc=0, k_ruv = 3,
                    adjust_bio="no",
                    return_norm = "in_memory",
                    zero = "postadjust")
  # NO RUV
  
  
  scores <- get_scores(my_scone)
  score_ranks <- get_score_ranks(my_scone)
  out_norm = get_normalized(my_scone,method = rownames(get_params(my_scone))[1])
  
  assay(sce79.4_qc, "scone") = log2(out_norm + 1)
})

detach("package:scone", unload=TRUE) 
detach("package:biomaRt", unload=TRUE) 

PCA_scone <- runPCA(sce79.4_qc, exprs_values = "scone")
p9 <- plotPCASCE(PCA_scone, colour_by = "group")+ ggtitle("scone")+ scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group)) + theme(legend.position="none")
sil9 <- calcSilhouette(PCA_scone, "scone")
```

## zinbwave

```{r}
library(zinbwave)
time_zinbwave <- system.time(
  se_norm <- zinbwave(sce79.4_qc, K=2, normalizedValues=TRUE,
                      residuals = TRUE)
)
assay(sce79.4_qc, "zinbwave") <- assay(se_norm, "normalizedValues")

PCA_zinbwave <- runPCA(sce79.4_qc, exprs_values = "zinbwave")
p10 <- plotPCASCE(PCA_zinbwave, colour_by = "group")+ ggtitle("zinbwave")+ scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group)) + theme(legend.position="none")
sil10 <- calcSilhouette(PCA_zinbwave, "zinbwave")
sil12 <- calcSilhouette(se_norm, "zinbwave W")
```

## SAVER + scran

```{r}
library(SAVER)

library(doParallel)
time_SAVER <- system.time({
registerDoParallel(cores = 64)
sce79.4_qc <- computeSumFactors(sce79.4_qc)
saver_out <- saver(counts(sce79.4_qc), size.factor = sizeFactors(sce79.4_qc))
#load("saver_out.RData")
assay(sce79.4_qc, "scran_SAVER") <- log2(saver_out$estimate + 1)
})

PCA_SAVER <- runPCA(sce79.4_qc, exprs_values = "scran_SAVER")
p11 <- plotPCASCE(PCA_SAVER, colour_by = "group")+ ggtitle("scran+SAVER")+ scale_fill_manual(values = unique(col), limits = unique(sce79.4_qc$group)) + theme(legend.position="none")
sil11 <- calcSilhouette(PCA_SAVER, "scran+SAVER")
```

## silhouette

```{r}
sil_all <- rbind(sil0, sil1, sil2, sil3, sil4, sil5, sil6, sil7, sil8, sil9,sil10, sil11, sil12, sil_knn)
ggplot(sil_all, aes(x = method, y=sil_width, fill=method)) + geom_boxplot() + stat_summary(fun.y=mean, geom="point",size=2) + theme_bw() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + theme(legend.position = "none")+ labs(x="method", y="silhouette width")

```

```{r}
# pdf("benchmark/PCA_9cell.pdf", width = 9)
multiplot(p0, p1,  p2, PCAk15, p3, p4, p5,p6,p8,p9,p10,p11,  cols = 4)
# dev.off()
```

###

<!-- ```{r} -->
<!-- cor_df_CPM <- cor_9cell_within(sce79.4_qc, "CPM") -->
<!-- cor_df_CPM_DrImpute <- cor_9cell_within(sce79.4_qc, "CPM_DrImpute") -->



<!-- cor_all <- rbind( -->
<!--   cbind(cor_df_raw, method = rep("raw count", nrow(cor_df_raw))), -->
<!--   # cbind(cor_df_knn, method = rep("knn3", nrow(cor_df_knn))), -->
<!--   cbind(cor_df_scran, method = rep("scran", nrow(cor_df_scran))), -->
<!--   cbind(cor_df_DrImpute, method = rep("scran+DrImpute", nrow(cor_df_DrImpute))), -->
<!--   cbind(cor_df_linnorm, method = rep("Linnorm", nrow(cor_df_linnorm))), -->
<!--   cbind(cor_df_DESeq, method = rep("DESeq", nrow(cor_df_linnorm))), -->
<!--   cbind(cor_df_CPM, method = rep("CPM", nrow(cor_df_CPM))), -->
<!--   cbind(cor_df_CPM_DrImpute, method =  rep("CPM+DrImpute", nrow(cor_df_CPM_DrImpute))) -->

<!-- ) -->

<!-- ggplot(data = cor_all, aes(x = factor(method), y = cor_val, fill = factor(method))) + geom_violin() + theme_bw() + ggtitle("correlation")+ stat_summary(fun.y=mean, geom="point",size=2) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- avg_d_raw = cal_knn_avg_distance(PCA_raw) -->
<!-- # avg_d_knn = cal_knn_avg_distance(PCA_knn) -->
<!-- avg_d_scran = cal_knn_avg_distance(PCA_scran) -->
<!-- avg_d_DrImpute = cal_knn_avg_distance(PCA_DrImpute) -->
<!-- avg_d_linnorm = cal_knn_avg_distance(PCA_linnorm) -->
<!-- avg_d_DESeq = cal_knn_avg_distance(PCA_DESeq) -->
<!-- avg_d_CPM = cal_knn_avg_distance(PCA_CPM) -->
<!-- avg_d_CPM_DrImpute = cal_knn_avg_distance(PCA_CPM_DrImpute) -->

<!-- avg_d_combine = data.frame( -->
<!--   avg_distance = c(avg_d_raw,  avg_d_scran, avg_d_DrImpute, avg_d_linnorm, avg_d_DESeq, avg_d_CPM, avg_d_CPM_DrImpute), -->
<!--   method = c(rep("raw count", length(avg_d_raw)),  rep("scran", length(avg_d_scran)), rep("scran+DrImpute", length(avg_d_DrImpute)), rep("Linnorm", length(avg_d_linnorm)), rep("DESeq", length(avg_d_DESeq)), rep("CPM", length(avg_d_CPM)), rep("CPM+DrImpute", length(avg_d_CPM_DrImpute))) -->
<!-- ) -->
<!-- ggplot(data = avg_d_combine, aes(x = factor(method), y = avg_distance, fill = factor(method))) + geom_violin() + theme_bw()+ ggtitle("average distance")+ stat_summary(fun.y=mean, geom="point",size=2) -->
<!-- ``` -->

# time

box plot coloured by time elapsed
```{r}
library(viridis)
time_all <- rbind(time_CPM, time_DESeq,  time_knn1, time_knn3, time_knn7, time_knn15, time_knn31, time_knn63, time_knn127, time_knn255, time_raw, time_scone, time_scran, time_TMM,  time_Linnorm, time_zinbwave, time_DrImpute, time_SAVER, time_BASiCS)
time_all <- data.frame(time_all)
time_all$method <- c("CPM", "DESeq",  "kNN (k=1)", "kNN (k=3)", "kNN (k=7)", "kNN (k=15)", "kNN (k=31)", "kNN (k=63)", "kNN (k=127)", "kNN (k=255)", "raw count",  "scone", "scran", "TMM", "Linnorm", "zinbwave", "scran+DrImpute", "scran+SAVER", "BASiCS")

time_all_sil <- merge(sil_all, time_all, by = "method")


```



```{r}
meanSil <- sapply(unique(time_all_sil$method), function(x){
  mean(time_all_sil[time_all_sil$method == x, "sil_width"])
}, simplify = TRUE)
medSil <- sapply(unique(time_all_sil$method), function(x){
  median(time_all_sil[time_all_sil$method == x, "sil_width"])
}, simplify = TRUE)
meanSil <- data.frame(meanSil, medSil, method = unique(time_all_sil$method))
meanSil <- merge(meanSil, time_all, by = "method")
meanSil$elapsed <- as.numeric(meanSil$elapsed)

write.csv(meanSil, "benchmark/9cell4_meanSil.csv")
```

```{r}
# pdf("benchmark/medsiltime_mRNA.pdf", height=4)
ggplot(meanSil, aes(log10(elapsed), medSil, colour= reorder(method, medSil)))  + geom_text(aes(label=method)) + labs(x="log10 running time lapse", y="median silhouette width") +theme_bw()+ theme(legend.position = "none")
# dev.off()
```


# save

```{r}
save.image("benchmark_9cell.4_120418.RData")
save(sce79.4_qc, file = "benchmark_SCE_9cell4.RData")
write.csv(sil_all, "benchmark/9cell4_sil_all.csv")
```

