---
title: "Imputation 10x"
author: "Xueyi Dong"
date: "2018/5/15"
output: html_document
---

```{r}
library(ggplot2)
library(scran)
library(scater)
library(cluster)
library(DrImpute)
library(SAVER)
library(doParallel)
```

# imputation

## linnorm+DrImute
```{r}
imp <- DrImpute(assay(sce2_qc, "linnorm"))
assay(sce2_qc, "linnorm_DrImpute") <- imp
```

## DESeq+DrImpute

```{r}
library(DrImpute)
time_DESeq_DrImpute <- system.time({
imp <- DrImpute(assay(sce2_qc, "DESeq"))
assay(sce2_qc, "DESeq_DrImpute") <- imp
})
time_DESeq_DrImpute <- time_DESeq_DrImpute + time_DESeq
```

## DESeq + SAVER

```{r}
library(SAVER)
library(doParallel)
time_DESeq_SAVER <- system.time({
  sizeFactors(sce2_qc) <- estimateSizeFactorsForMatrix(counts(sce2_qc))
  registerDoParallel(cores = 64)
  saver_out <- saver(counts(sce2_qc), size.factor = sizeFactors(sce2_qc))
  #load("saver_out.RData")
  assay(sce2_qc, "DESeq_SAVER") <- log2(saver_out$estimate + 1)
})
```

## CPM+DrImpute

```{r}
library(DrImpute)

imp <- DrImpute(assay(sce2_qc, "norm_cpm"))
assay(sce2_qc, "CPM_DrImpute") <- imp

```

## CPM + SAVER

```{r}
library(SAVER)
library(doParallel)
time_DESeq_SAVER <- system.time({
  
  assay(sce2_qc, "cpm") = cpm(counts(sce2_qc))
  registerDoParallel(cores = 64)
  saver_out <- saver(assay(sce2_qc, "cpm"), size.factor = 1)
  #load("saver_out.RData")
  assay(sce2_qc, "CPM_SAVER") <- log2(saver_out$estimate + 1)
})
```

## calculate

```{r}
PCA_DESeq_DrImpute <- runPCA(sce2_qc, exprs_values = "DESeq_DrImpute", ncomponents = 2)
PCA_DESeq_SAVER <- runPCA(sce2_qc, exprs_values = "DESeq_SAVER")

sil_DESeq_DrImpute <- calcSilhouette(PCA_DESeq_DrImpute, "DESeq+DrImpute")
sil_DESeq_SAVER <- calcSilhouette(PCA_DESeq_SAVER, "DESeq+SAVER")
f1_DESeq_DrImpute <- calculateF(PCA_DESeq_DrImpute, 1)
f2_DESeq_DrImpute <- calculateF(PCA_DESeq_DrImpute, 2)
f1_DESeq_SAVER <- calculateF(PCA_DESeq_SAVER, 1)
f2_DESeq_SAVER <- calculateF(PCA_DESeq_SAVER, 2)
```


```{r}
PCA_CPM_DrImpute <- runPCA(sce2_qc, exprs_values = "CPM_DrImpute", ncomponents = 2)
PCA_CPM_SAVER <- runPCA(sce2_qc, exprs_values = "CPM_SAVER")

sil_CPM_DrImpute <- calcSilhouette(PCA_CPM_DrImpute, "CPM+DrImpute")
sil_CPM_SAVER <- calcSilhouette(PCA_CPM_SAVER, "CPM+SAVER")
f1_CPM_DrImpute <- calculateF(PCA_CPM_DrImpute, 1)
f2_CPM_DrImpute <- calculateF(PCA_CPM_DrImpute, 2)
f1_CPM_SAVER <- calculateF(PCA_CPM_SAVER, 1)
f2_CPM_SAVER <- calculateF(PCA_CPM_SAVER, 2)
```

```{r}
PCA_linnorm_DrImpute <- runPCA(sce2_qc, exprs_values = "linnorm_DrImpute", ncomponents = 2)


sil_linnorm_DrImpute <- calcSilhouette(PCA_linnorm_DrImpute, "linnorm+DrImpute")

f1_linnorm_DrImpute <- calculateF(PCA_linnorm_DrImpute, 1)
f2_linnorm_DrImpute <- calculateF(PCA_linnorm_DrImpute, 2)

```


# Results integration

add new rows to the original silhouette width all data frame.

```{r}
sil_all <- rbind(sil_all, sil_DESeq_DrImpute, sil_DESeq_SAVER, sil_linnorm_DrImpute, sil_CPM_DrImpute, sil_CPM_SAVER)

f1_new <- data.frame(f=c(f1_DESeq_DrImpute,f1_DESeq_SAVER, f1_linnorm_DrImpute, f1_CPM_DrImpute, f1_CPM_SAVER), method=c("DESeq+DrImpute", "DESeq+SAVER", "Linnorm+DrImpute", "CPM+DrImpute", "CPM+SAVER"))
f2_new <- data.frame(f=c(f2_DESeq_DrImpute,f2_DESeq_SAVER, f2_linnorm_DrImpute, f2_CPM_DrImpute, f2_CPM_SAVER), method=c("DESeq+DrImpute", "DESeq+SAVER", "Linnorm+DrImpute", "CPM+DrImpute", "CPM+SAVER"))

f <- rbind(f, f1_new)
f2 <- rbind(f2, f2_new)
```

```{r}
write.csv(sil_all, file = "imputation/mRNA_sil.csv")
write.csv(f, file = "imputation/mRNA_f1.csv")
write.csv(f2, file = "imputation/mRNA_f2.csv")
```

```{r}
cor1 <- cor_mRNAmix_within(sce2_qc, "DESeq_DrImpute")
cor1$method <- "DESeq+DrImpute"
cor2 <- cor_mRNAmix_within(sce2_qc, "DESeq_SAVER")
cor2$method <- "DESeq+SAVER"
cor3 <- cor_mRNAmix_within(sce2_qc, "linnorm_DrImpute")
cor3$method <- "Linnorm+DrImpute"
cor4 <- cor_mRNAmix_within(sce2_qc, "CPM_DrImpute")
cor4$method <- "CPM+DrImpute"
cor5 <- cor_mRNAmix_within(sce2_qc, "CPM_SAVER")
cor5$method <- "CPM+SAVER"

cor_df_all <- rbind(cor_df_all, cor1, cor2, cor3, cor4, cor5)

write.csv(cor_df_all, file = "imputation/mRNA_cor.csv")
```


