---
title: "QC for NN84"
output: html_notebook
---

```{r library, message=FALSE}
library(scPipe)
```

```{r}
Diluted1 <- "/Volumes/singlecellRNAseq/NN84_15.01.18/RPI2"
Diluted2 <- "/Volumes/singlecellRNAseq/NN84_15.01.18/RPI4"
Diluted3 <- "/Volumes/singlecellRNAseq/NN84_15.01.18/RPI8"
#Diluted4 <- "/wehisan/general/user_managed/grpu_naik.s_1/NN84_15.01.18/Undetermined/gene_count.csv"
design <- "NN84_mRNA_annotation_correct.csv"

sce2 <- create_sce_by_dir(Diluted1, organism="hsapiens_gene_ensembl", gene_id_type="ensembl_gene_id")
sce8 <- create_sce_by_dir(Diluted3, organism="hsapiens_gene_ensembl", gene_id_type="ensembl_gene_id")
```

```{r}
sce2=calculate_QC_metrics(sce2)
sce8=calculate_QC_metrics(sce8)
```

```{r}
NN84_mRNA_annotation <- read.csv(design, stringsAsFactors=FALSE)
NN84_mRNA_annotation = NN84_mRNA_annotation[match(colnames(sce2),NN84_mRNA_annotation$cell_name),]
colData(sce2) = cbind(colData(sce2), DataFrame(NN84_mRNA_annotation))
colData(sce8) = cbind(colData(sce8), DataFrame(NN84_mRNA_annotation))
```

QC

```{r}
sce2_qc = detect_outlier(sce2, type="low", comp = 2)
table(QC_metrics(sce2_qc)$outliers)

sce8_qc = detect_outlier(sce8, type="low", comp = 2)
table(QC_metrics(sce8_qc)$outliers)

sce8_qc = remove_outliers(sce8_qc)
sce2_qc = remove_outliers(sce2_qc)
```



QC

```{r}
keep1 = (apply(counts(sce2_qc), 1, function(x) mean(x[x>0])) > 1)  # average count larger than 1
keep2 = (rowSums(counts(sce2_qc)>0) > 10)  
table(keep1&keep2)
sce2_qc = sce2_qc[(keep1 & keep2), ]

keep1 = (apply(counts(sce8_qc), 1, function(x) mean(x[x>0])) > 1)  # average count larger than 1
keep2 = (rowSums(counts(sce8_qc)>0) > 10)  
table(keep1&keep2)
sce8_qc = sce8_qc[(keep1 & keep2), ]
```

```{r}
is.spike2 <- grepl("^ERCC", rownames(sce2_qc))
is.spike8 <- grepl("^ERCC", rownames(sce8_qc))

sce2_qc <- calculateQCMetrics(sce2_qc, feature_controls = list(ERCC = is.spike2))
sce8_qc <- calculateQCMetrics(sce8_qc, feature_controls = list(ERCC = is.spike8))
save.image("SCE.RData")
```
normalization

```{r}
library(scran)
library(scater)

sce2_qc <- computeSumFactors(sce2_qc)
sce2_qc <- computeSpikeFactors(sce2_qc)
sce2_qc <- normalize(sce2_qc)

sce8_qc <- computeSumFactors(sce8_qc)
sce8_qc <- computeSpikeFactors(sce8_qc)
sce8_qc <- normalize(sce8_qc)
```


# check cell identity

The original annotation of NN84 was wrong.

```{r}
library(edgeR)
bulk.count.matrix <- read.delim("/Volumes/MattLab/Mixture/Pilot/reverse.stranded.unfiltered.count.matrix.txt", row.names=1, stringsAsFactors=FALSE)
bulk.count.matrix = bulk.count.matrix[,c("RSCE_6_BC2CTUACXX_CTTGTA_L005_R1.bam", "RSCE_8_BC2CTUACXX_CCGTCC_L007_R1.bam",
                                         "RSCE_10_BC2CTUACXX_AGTTCC_L006_R1.bam", "RSCE_12_BC2CTUACXX_TGACCA_L005_R1.bam",
                                         "RSCE_14_BC2CTUACXX_GTCCGC_L003_R1.bam", "RSCE_16_BC2CTUACXX_AGTTCC_L004_R1.bam")]
colnames(bulk.count.matrix) = c("H1975_rep1", "H1975_rep2",
                                "HCC827_rep1", "HCC827_rep2",
                                "H2228_rep1", "H2228_rep2")
grp = c("H1975","H1975","HCC827","HCC827","H2228","H2228")
y = DGEList(counts=bulk.count.matrix, group = grp)
y = estimateCommonDisp(y)

design <- model.matrix(~0+grp)
fit = glmFit(y,design=design)
contrasts = makeContrasts(
    H2228=grpH2228-0.5*grpH1975-0.5*grpHCC827,
    H1975=grpH1975-0.5*grpHCC827-0.5*grpH2228,
    HCC827=grpHCC827-0.5*grpH2228-0.5*grpH1975,
    levels=colnames(design))

lrt = glmLRT(fit, contrast=contrasts[,1])
H2228 = topTags(lrt,n=500,p.value=0.001)

lrt = glmLRT(fit, contrast=contrasts[,2])
H1975 = topTags(lrt,n=500,p.value=0.001)

lrt = glmLRT(fit, contrast=contrasts[,3])
HCC827 = topTags(lrt,n=500,p.value=0.001)
```

```{r}

sce2_qc_sel <- convert_geneid(sce2_qc, returns = "entrezgene")
```

```{r}
bulk.count.matrix = bulk.count.matrix[rownames(bulk.count.matrix) %in% c(rownames(H2228), rownames(H1975), rownames(HCC827)),]
uni_genes = intersect(rownames(bulk.count.matrix), rownames(sce2_qc_sel))

bulk_mat_sel = bulk.count.matrix[uni_genes,]
sce2_qc_sel = sce2_qc_sel[uni_genes,]
```

```{r}
H1975 = apply(logcounts(sce2_qc_sel), 2, function(x){cor(bulk_mat_sel[,"H1975_rep1"], x, method="spearman")})
H2228 = apply(logcounts(sce2_qc_sel), 2, function(x){cor(bulk_mat_sel[,"HCC827_rep1"], x, method="spearman")})
HCC827 = apply(logcounts(sce2_qc_sel), 2, function(x){cor(bulk_mat_sel[,"H2228_rep1"], x, method="spearman")})
cor_mat = data.frame(H1975, H2228, HCC827, stringsAsFactors = F)
cor_mat$cell = rownames(cor_mat)
cor_mat_mix <- merge(cor_mat, NN84_mRNA_annotation, by.x = "cell", by.y = "cell_name")
cor_mat_mix$mix <- as.factor(cor_mat_mix$mix)
write.csv(cor_mat_mix, "mRNAmix_cor_anno.csv")
```

```{r}
library(ggplot2)
library(ggridges)
pdf("NN84.pdf")
ggplot(cor_mat_mix, aes(x = H1975, y = mix, fill = H1975_prop)) + geom_density_ridges() + theme_ridges() + ggtitle("H1975")
ggplot(cor_mat_mix, aes(x = H2228, y = mix, fill = H2228_prop)) + geom_density_ridges() + theme_ridges() + ggtitle("H2228")
ggplot(cor_mat_mix, aes(x = HCC827, y = mix, fill = HCC827_prop)) + geom_density_ridges() + theme_ridges() + ggtitle("HCC827")
dev.off()
```

