---
title: "Benchmarking for imputation methods of single cell data sets"
author: "董雪漪"
date: "2018/5/15"
output: html_document
---

```{r}
library(ggplot2)
library(scran)
library(scater)
```

Function for ANOVA and return F-statistic
```{r}
calculateF <- function(SCE, n=1){
  data <- cbind(reducedDim(SCE), colData(SCE))
  g <- lm(data[,n]~data[,"cell_line"])
  return(anova(g)$F[1])
}
```

Function for calculate silhouette width of PCA analysis, group samples according to their cell type

```{r}
library(cluster)

calcSilhouette <- function(SCE, name){
  sil <- silhouette(as.numeric(factor(SCE$cell_line)), dist(reducedDim(SCE)))
  sil <- data.frame(sil[1:nrow(sil),])
  method <- rep(name, nrow(sil))
  sil <- cbind(sil, method)
}
```

# Imputation

already run: scran, CPM, linnorm

## DESeq+DrImpute

```{r}
library(DrImpute)
time_DESeq_DrImpute <- system.time({
imp <- DrImpute(assay(sce4_qc, "DESeq"))
assay(sce4_qc, "DESeq_DrImpute") <- imp
})
time_DESeq_DrImpute <- time_DESeq_DrImpute + time_DESeq
```

## DESeq + SAVER

```{r}
library(SAVER)
library(doParallel)
time_DESeq_SAVER <- system.time({
  sizeFactors(sce4_qc) <- estimateSizeFactorsForMatrix(counts(sce4_qc))
  registerDoParallel(cores = 64)
  saver_out <- saver(counts(sce4_qc), size.factor = sizeFactors(sce4_qc))
  #load("saver_out.RData")
  assay(sce4_qc, "DESeq_SAVER") <- log2(saver_out$estimate + 1)
})
```


## calculate

```{r}
PCA_DESeq_DrImpute <- runPCA(sce4_qc, exprs_values = "DESeq_DrImpute", ncomponents = 2)
# PCA_DESeq_SAVER <- runPCA(sce4_qc, exprs_values = "DESeq_SAVER")

sil_DESeq_DrImpute <- calcSilhouette(PCA_DESeq_DrImpute, "DESeq+DrImpute")
# sil_DESeq_SAVER <- calcSilhouette(PCA_DESeq_SAVER, "DESeq+SAVER")
f1_DESeq_DrImpute <- calculateF(PCA_DESeq_DrImpute, 1)
f2_DESeq_DrImpute <- calculateF(PCA_DESeq_DrImpute, 2)
# f1_DESeq_SAVER <- calculateF(PCA_DESeq_SAVER, 1)
# f2_DESeq_SAVER <- calculateF(PCA_DESeq_SAVER, 2)
```


```{r}
sil_linnorm_DrImpute <- calcSilhouette(linnorm_DrImpute_100, "Linnorm+DrImpute")
f1_linnorm_DrImpute <- calculateF(linnorm_DrImpute_100, 1)
f2_linnorm_DrImpute <- calculateF(linnorm_DrImpute_100, 2)
```

```{r}
sil_CPM_DrImpute <- calcSilhouette(CPM_DrImpute_100, "CPM+DrImpute")
f1_CPM_DrImpute <- calculateF(CPM_DrImpute_100, 1)
f2_CPM_DrImpute <- calculateF(CPM_DrImpute_100, 2)
```

```{r}
sil_CPM_SAVER <- calcSilhouette(CPM_SAVER_100, "CPM+SAVER")
f1_CPM_SAVER <- calculateF(CPM_SAVER_100, 1)
f2_CPM_SAVER <- calculateF(CPM_SAVER_100, 2)
```

# Results integration

add new rows to the original silhouette width all data frame.

```{r}
sil_all <- rbind(sil_all, sil_DESeq_DrImpute, sil_linnorm_DrImpute, sil_CPM_DrImpute, sil_CPM_SAVER)

f1_new <- data.frame(f=c(f1_DESeq_DrImpute, f1_linnorm_DrImpute, f1_CPM_DrImpute, f1_CPM_SAVER), method=c("DESeq+DrImpute", "Linnorm+DrImpute", "CPM+DrImpute", "CPM+SAVER"))
f2_new <- data.frame(f=c(f2_DESeq_DrImpute, f2_linnorm_DrImpute, f2_CPM_DrImpute, f2_CPM_SAVER), method=c("DESeq+DrImpute", "Linnorm+DrImpute", "CPM+DrImpute", "CPM+SAVER"))

f <- rbind(f, f1_new)
f2 <- rbind(f2, f2_new)
```

```{r}
write.csv(sil_all, file = "imputation/sc_sil.csv")
write.csv(f, file = "imputation/sc_f1.csv")
write.csv(f2, file = "imputation/sc_f2.csv")
```

