---
title: "cellmix34 clustering"
output: html_notebook
---

```{r, warning=FALSE,message=FALSE}
setwd("/stornext/General/data/user_managed/grpu_mritchie_1/SCmixology/analysis_for_resubmit")
library(scran)
library(scater)
library(CellBench)
set_cellbench_threads(nthreads = 1)

log_file =paste("log_file/clustering_cellmix34",format(Sys.time(), "%a_%b_%d"),".txt",sep = ".")
cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "start preprocessing..."), file = log_file, append = TRUE)
```

# load all data 

# make a list of dataset for `Cellbench`

```{r}
res2 = readRDS("/stornext/General/data/user_managed/grpu_mritchie_1/SCmixology/analysis_for_resubmit/rdata/cellmix34_after_imputation.Rds")
```


```{r}
scran_high_var = function(sce,topn=1000){
  var.fit <- trendVar(sce, method="loess", use.spikes=FALSE)
  var.out <- decomposeVar(sce, var.fit)
  hvg.out <- var.out[order(var.out$bio, decreasing=TRUE)[1:topn], ]
  rowData(sce)$hi_var = FALSE
  rowData(sce)$hi_var[rownames(rowData(sce)) %in% rownames(hvg.out)] = TRUE
  return(sce)
}
```


```{r}
library(biomaRt)
mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
G_list <- getBM(filters="ensembl_gene_id",
                attributes=c("external_gene_name","ensembl_gene_id","external_gene_source"),
                values=rownames(res2$result[[1]]),
                mart=mart)

G_list = G_list[G_list$external_gene_source == "HGNC Symbol",]
G_list$format_name = paste("XXXX",G_list$external_gene_name,G_list$ensembl_gene_id,sep="_")
rownames(G_list) = G_list$ensembl_gene_id
format_rowname = function(sce){
  sce = sce[rownames(sce) %in% G_list$ensembl_gene_id,]
  rownames(sce) = G_list[rownames(sce),"format_name"]
  return(sce)
}

hivar_method = list(scran_hi = scran_high_var)
format_method = list(format_rowname=format_rowname)
```

 

# set the clustering methods

```{r}
library(Seurat)
library(RaceID)
library(RCA)
#library(SC3)
NUM_OF_THREAD=8

Seurat_c.8 = function(sce){
  tp = system.time({
  srt = CreateSeuratObject(raw.data = counts(sce),display.progress = FALSE)
  srt@scale.data = logcounts(sce)
  if("hi_var" %in% colnames(rowData(sce))){
    srt@var.genes = rownames(sce)[rowData(sce)$hi_var]
  }
  
  srt = RunPCA(srt, pc.genes = srt@var.genes, seed.use=42, do.print=FALSE)
  srt = FindClusters(object = srt, reduction.type = "pca", 
                         dims.use = 1:5,  print.output = FALSE, save.SNN = FALSE,
                         genes.use = NULL,
                         k.param = 30, plot.SNN = FALSE, prune.SNN = 1/15,
                         distance.matrix = NULL, 
                         reuse.SNN = FALSE, force.recalc = FALSE, nn.eps = 0,
                         modularity.fxn = 1, resolution = 0.8, algorithm = 1, n.start = 100,
                         n.iter = 10, random.seed = 0)
  
  colData(sce)$clustering_res = as.factor(srt@ident)
  })
  
  method_name = "Seurat_0.8"
  method_type = "clustering"
  if (!is.null(metadata(sce)$running_time)){
    metadata(sce)$running_time = rbind(metadata(sce)$running_time, data.frame(method=method_name, method_type=method_type, time=unname(tp)[1]))
  }else{
    metadata(sce)$running_time = data.frame(method=method_name,method_type=method_type,time=unname(tp)[1])
  }
  return(sce)
}


Seurat_pipe = function(sce){
  tp = system.time({
  srt = CreateSeuratObject(raw.data = counts(sce),display.progress = FALSE)
  srt = NormalizeData(object = srt, normalization.method = "LogNormalize", scale.factor = 10000,
                      assay.type = "RNA", display.progress = FALSE)
  srt = FindVariableGenes(object = srt, mean.function = ExpMean, dispersion.function = LogVMR, 
                                x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5,
                                y.high.cutoff = Inf, num.bin = 20, binning.method = "equal_width",
                                selection.method = "mean.var.plot", top.genes = 1000, do.recalc = TRUE,
                                sort.results = TRUE, do.cpp = TRUE, display.progress = FALSE,do.plot = FALSE)
  srt = ScaleData(object = srt)
  srt = RunPCA(srt, pc.genes = srt@var.genes, seed.use=42, do.print=FALSE)
  srt = FindClusters(object = srt, reduction.type = "pca", 
                         dims.use = 1:5,  print.output = FALSE, save.SNN = FALSE,
                         genes.use = NULL,
                         k.param = 30, plot.SNN = FALSE, prune.SNN = 1/15,
                         distance.matrix = NULL, 
                         reuse.SNN = FALSE, force.recalc = FALSE, nn.eps = 0,
                         modularity.fxn = 1, resolution = 0.8, algorithm = 1, n.start = 100,
                         n.iter = 10, random.seed = 0)
  
  colData(sce)$clustering_res = as.factor(srt@ident)
  })
  
  method_name = "Seurat_pipe"
  method_type = "clustering"
  if (!is.null(metadata(sce)$running_time)){
    metadata(sce)$running_time = rbind(metadata(sce)$running_time, data.frame(method=method_name, method_type=method_type, time=unname(tp)[1]))
  }else{
    metadata(sce)$running_time = data.frame(method=method_name,method_type=method_type,time=unname(tp)[1])
  }
  return(sce)
}


Seurat_c1.4 = function(sce){
  tp = system.time({
  srt = CreateSeuratObject(raw.data = counts(sce),display.progress = FALSE)
  srt@scale.data = logcounts(sce)
  if("hi_var" %in% colnames(rowData(sce))){
    srt@var.genes = rownames(sce)[rowData(sce)$hi_var]
  }
  
  srt = RunPCA(srt, pc.genes = srt@var.genes, seed.use=42, do.print=FALSE)
  srt = FindClusters(object = srt, reduction.type = "pca", 
                         dims.use = 1:5,  print.output = FALSE, save.SNN = FALSE,
                         genes.use = NULL,
                         k.param = 30, plot.SNN = FALSE, prune.SNN = 1/15,
                         distance.matrix = NULL, 
                         reuse.SNN = FALSE, force.recalc = FALSE, nn.eps = 0,
                         modularity.fxn = 1, resolution = 1.4, algorithm = 1, n.start = 100,
                         n.iter = 10, random.seed = 0)
  
  colData(sce)$clustering_res = as.factor(srt@ident)
  })
  
  method_name = "Seurat_1.4"
  method_type = "clustering"
  if (!is.null(metadata(sce)$running_time)){
    metadata(sce)$running_time = rbind(metadata(sce)$running_time, data.frame(method=method_name, method_type=method_type, time=unname(tp)[1]))
  }else{
    metadata(sce)$running_time = data.frame(method=method_name,method_type=method_type,time=unname(tp)[1])
  }
  return(sce)
}


RaceID3_c = function(sce){
  tp = system.time({
    try_res = try({
      var.genes = rownames(sce)[rowData(sce)$hi_var]
      tmp = logcounts(sce)[var.genes,]
      sc <- SCseq(as.data.frame(as.matrix(tmp)))
      sc <- filterdata(sc, mintotal=1, minexpr = 1, minnumber = 1,
                       LBatch = NULL, knn = 10, CGenes = NULL, FGenes = NULL, ccor = 0.4,
                       bmode = "RaceID")
      sc@ndata = sc@expdata
      sc@genes = rownames(sc@ndata)
      sc@counts = rep(1,ncol(sce))
      names(sc@counts) = colnames(sc@ndata)
      sc@cluster$features = sc@genes
      sc <- compdist(sc, metric="pearson", FSelect = FALSE, knn = NULL)
      sc <- clustexp(sc, sat = TRUE, samp = NULL, cln = NULL, clustnr = 30,
                     bootnr = 50, rseed = 17000, FUNcluster = "kmedoids")
      sc <- findoutliers(sc, probthr = 0.001, outminc = 5, outlg = 2,
                         outdistquant = 0.95)
      colData(sce)$clustering_res = as.factor(sc@cpart)
    })
    if (class(try_res) == "try-error") {
      cat(paste(format(Sys.time(), "%a %b %d %X %Y. ERROR: "), print(try_res),"\n"), file = log_file, append = TRUE)
    }
  })
  
  method_name = "RaceID3"
  method_type = "clustering"
  if (!is.null(metadata(sce)$running_time)){
    metadata(sce)$running_time = rbind(metadata(sce)$running_time, data.frame(method=method_name, method_type=method_type, time=unname(tp)[1]))
  }else{
    metadata(sce)$running_time = data.frame(method=method_name,method_type=method_type,time=unname(tp)[1])
  }
  return(sce)
}


RCA_c = function(sce){
  tp = system.time({
    try_res = try({
      var.genes = rownames(sce)[rowData(sce)$hi_var]
      tmp = logcounts(sce)[var.genes,]
      obj = as.matrix(tmp)
      obj = obj^10 # the `dataTransform` is necessary so we have to do this extra step
      data_obj = dataConstruct(obj)
      data_obj = geneFilt(obj_in = data_obj);
      data_obj = cellNormalize(data_obj);
      data_obj = dataTransform(data_obj,"log10")
      data_obj = featureConstruct(data_obj, method = "GlobalPanel")
      set.seed(20742579)
      data_obj = cellClust(data_obj, method = "hclust", deepSplit_wgcna = 1,
                          min_group_Size_wgcna = 5)
      colData(sce)$clustering_res <- data_obj$group_labels_color$groupLabel
    })
    if (class(try_res) == "try-error") {
      cat(paste(format(Sys.time(), "%a %b %d %X %Y. ERROR: "), print(try_res),"\n"), file = log_file, append = TRUE)
    }
  })
  
  method_name = "RCA"
  method_type = "clustering"
  if (!is.null(metadata(sce)$running_time)){
    metadata(sce)$running_time = rbind(metadata(sce)$running_time, data.frame(method=method_name, method_type=method_type, time=unname(tp)[1]))
  }else{
    metadata(sce)$running_time = data.frame(method=method_name,method_type=method_type,time=unname(tp)[1])
  }
  return(sce)
}


# SC3_c = function(sce){
#   tp = system.time({
#     try_res = try({
#       rowData(sce)$feature_symbol <- rownames(sce)
#       sce = sce[rowData(sce)$hi_var,]
#       sce <- sc3_estimate_k(sce)
#       k_est <- sce@metadata$sc3$k_estimation
#       sce <- sc3(sce, ks = k_est, biology = FALSE, n_cores=NUM_OF_THREAD,  k_estimator = FALSE, rand_seed=2333333)
#       
#       eval(parse(text=paste0("colData(sce)$clustering_res <- colData(sce)$sc3_", k_est, "_clusters")))
#       })
#       if (class(try_res) == "try-error") {
#         cat(paste(format(Sys.time(), "%a %b %d %X %Y. ERROR: "), print(try_res),"\n"), file = log_file, append = TRUE)
#       }
#   })
#   
#   method_name = "SC3"
#   method_type = "clustering"
#   if (!is.null(metadata(sce)$running_time)){
#     metadata(sce)$running_time = rbind(metadata(sce)$running_time, data.frame(method=method_name, method_type=method_type, time=unname(tp)[1]))
#   }else{
#     metadata(sce)$running_time = data.frame(method=method_name,method_type=method_type,time=unname(tp)[1])
#   }
#   return(sce)
# }


clustering_method <- list(
    Seurat_0.8 = Seurat_c.8,
    Seurat_1.4 = Seurat_c1.4,
    RaceID3=RaceID3_c,
    RCA=RCA_c,
    Seurat_pipe=Seurat_pipe
)
```


# apply clustering

```{r, warning=FALSE,message=FALSE}
cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "start to apply clustering methods...\n"), file = log_file, append = TRUE)

res2 = res2 %>% apply_methods(format_method)

res2 = res2 %>% apply_methods(hivar_method)

res2 = res2[,!(colnames(res2) %in% c("format_method","hivar_method"))]

res_c <- res2 %>%
    apply_methods(clustering_method)

cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "finish all clustering methods...\n"), file = log_file, append = TRUE)
```

```{r}

clean_sce = function(sce){ # remove expr data after clustering to save space
  logcounts(sce) = NULL
  counts(sce) = NULL
  return(sce)
}
clean_up = list(cl = clean_sce)

res_c = res_c %>% apply_methods(clean_up)
res_c = res_c[,!(colnames(res_c) %in% c("clean_up"))]
```



```{r}
saveRDS(res_c, file="/stornext/General/data/user_managed/grpu_mritchie_1/SCmixology/analysis_for_resubmit/rdata/cellmix34_after_clustering.Rds")
```


# apply metrics for evaluation

```{r}
library(mclust)


ARI_matric = function(sce){
  if(!("clustering_res" %in% colnames(colData(sce)))){
    return(NA)
  }
  if ("group" %in% colnames(colData(sce))){
    ari_val = adjustedRandIndex(sce$group, sce$clustering_res)
  }else{
    ari_val = adjustedRandIndex(sce$cell_line, sce$clustering_res)
  }

  return(ari_val)
}

clustering_evaluation <- list(
  ARI=ARI_matric
)

res_ARI <- res_c %>%
    apply_methods(clustering_evaluation)
```


```{r}
ggplot(data=res_ARI,aes(x=clustering_method,y=result,col=impute_method))+geom_boxplot()+theme_bw()
```

```{r}
ggplot(data=res_ARI,aes(x=clustering_method,y=result,col=norm_method))+geom_boxplot()+theme_bw()
```



```{r}
cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "cellmix34 Done! saved the result to file.\n"), file = log_file, append = TRUE)
```


