---
title: "BASiCS normalization on RNAmix"
output: html_notebook
---

```{r}
setwd("/stornext/General/data/user_managed/grpu_mritchie_1/SCmixology/analysis_for_resubmit")
library(BASiCS)
library(scater)
library(scran)

log_file =paste("log_file/BASiCS_norm_cellmix_spike",format(Sys.time(), "%a_%b_%d"),".txt",sep = ".")
cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "start preprocessing...\n"), file = log_file, append = TRUE)
```

The BASiCS normalization is time comsuming so we run it separately.

## prepare dataset and preprocessing
```{r}
load("CellBench_data/data/9cellmix_qc.RData")

gene_filter = function(sce){
  keep1 = (apply(counts(sce), 1, function(x) mean(x[x>0])) > 1.1)  # average count larger than 1.1
  keep2 = (rowSums(counts(sce)>0) > 10) # expressed in more than 10 cells
  sp_keep = colSums(counts(sce)[isSpike(sce),])>0
  sce = sce[(keep1 & keep2), sp_keep]
  return(sce)
}
sce_SC1_qc = gene_filter(sce_SC1_qc)
sce_SC2_qc = gene_filter(sce_SC2_qc)
sce_SC3_qc = gene_filter(sce_SC3_qc)
sce_SC4_qc = gene_filter(sce_SC4_qc)

cms_095046 <- read.delim("cms_095046.txt", stringsAsFactors = FALSE)
method_name = "BASiCS"
method_type = "norm"
```


```{r}
sce_SC1_qc <- sce_SC1_qc[order(isSpike(sce_SC1_qc)),]
SpikeInfo = data.frame(ERCCID=cms_095046$ERCC.ID, count=cms_095046$concentration.in.Mix.1..attomoles.ul.)
SpikeInfo = SpikeInfo[SpikeInfo$ERCCID %in% rownames(sce_SC1_qc)[isSpike(sce_SC1_qc)],]
rownames(SpikeInfo) = SpikeInfo$ERCCID
SpikeInfo[,2] = SpikeInfo[,2]/(166.0541*9) # 1/9 sampled for each well.
metadata(sce_SC1_qc) <- list(SpikeInput = SpikeInfo[rownames(sce_SC1_qc)[isSpike(sce_SC1_qc)],2])

cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "start MCMC.\n"), file = log_file, append = TRUE)
tp = system.time({
ChainNoSpikes <- BASiCS_MCMC(Data = sce_SC1_qc, N = 5000, 
                             Thin = 10, Burn = 500, 
                             WithSpikes = TRUE,Regression = TRUE,
                             PrintProgress = FALSE,
                             StoreChains=TRUE,
                             RunName="cellmix1_BASiCS_spike")
})
cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "MCMC finished.\n"), file = log_file, append = TRUE)

DenoisedCounts <- BASiCS_DenoisedCounts(Data = sce_SC1_qc, Chain = ChainNoSpikes)
logcounts(sce_SC1_qc) = log2(DenoisedCounts+1)
metadata(sce_SC1_qc)$running_time = data.frame(method=method_name,method_type=method_type,time=unname(tp)[1])

saveRDS(sce_SC1_qc,file="cellmix1_BASiCS_Spike_SCE.Rds")
cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "cellmix1 Done! save the normalized count to file.\n"), file = log_file, append = TRUE)
```



```{r}
sce_SC2_qc <- sce_SC2_qc[order(isSpike(sce_SC2_qc)),]
SpikeInfo = data.frame(ERCCID=cms_095046$ERCC.ID, count=cms_095046$concentration.in.Mix.1..attomoles.ul.)
SpikeInfo = SpikeInfo[SpikeInfo$ERCCID %in% rownames(sce_SC2_qc)[isSpike(sce_SC2_qc)],]
rownames(SpikeInfo) = SpikeInfo$ERCCID
SpikeInfo[,2] = SpikeInfo[,2]/(166.0541*9)
metadata(sce_SC2_qc) <- list(SpikeInput = SpikeInfo[rownames(sce_SC2_qc)[isSpike(sce_SC2_qc)],2])

cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "start MCMC.\n"), file = log_file, append = TRUE)
tp = system.time({
ChainNoSpikes <- BASiCS_MCMC(Data = sce_SC2_qc, N = 5000, 
                             Thin = 10, Burn = 500, 
                             WithSpikes = TRUE,Regression = TRUE,
                             PrintProgress = FALSE,
                             StoreChains=TRUE,
                             RunName="cellmix2_BASiCS_spike")
})
cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "MCMC finished.\n"), file = log_file, append = TRUE)

DenoisedCounts <- BASiCS_DenoisedCounts(Data = sce_SC2_qc, Chain = ChainNoSpikes)
logcounts(sce_SC2_qc) = log2(DenoisedCounts+1)
metadata(sce_SC2_qc)$running_time = data.frame(method=method_name,method_type=method_type,time=unname(tp)[1])

saveRDS(sce_SC2_qc,file="cellmix2_BASiCS_Spike_SCE.Rds")
cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "cellmix2 Done! save the normalized count to file.\n"), file = log_file, append = TRUE)
```


```{r}
sce_SC3_qc <- sce_SC3_qc[order(isSpike(sce_SC3_qc)),]
SpikeInfo = data.frame(ERCCID=cms_095046$ERCC.ID, count=cms_095046$concentration.in.Mix.1..attomoles.ul.)
SpikeInfo = SpikeInfo[SpikeInfo$ERCCID %in% rownames(sce_SC3_qc)[isSpike(sce_SC3_qc)],]
rownames(SpikeInfo) = SpikeInfo$ERCCID
SpikeInfo[,2] = SpikeInfo[,2]/(166.0541*9)
metadata(sce_SC3_qc) <- list(SpikeInput = SpikeInfo[rownames(sce_SC3_qc)[isSpike(sce_SC3_qc)],2])

cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "start MCMC.\n"), file = log_file, append = TRUE)
tp = system.time({
ChainNoSpikes <- BASiCS_MCMC(Data = sce_SC3_qc, N = 5000, 
                             Thin = 10, Burn = 500, 
                             WithSpikes = TRUE,Regression = TRUE,
                             PrintProgress = FALSE,
                             StoreChains=TRUE,
                             RunName="cellmix3_BASiCS_spike")
})
cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "MCMC finished.\n"), file = log_file, append = TRUE)

DenoisedCounts <- BASiCS_DenoisedCounts(Data = sce_SC3_qc, Chain = ChainNoSpikes)
logcounts(sce_SC3_qc) = log2(DenoisedCounts+1)
metadata(sce_SC3_qc)$running_time = data.frame(method=method_name,method_type=method_type,time=unname(tp)[1])

saveRDS(sce_SC3_qc,file="cellmix3_BASiCS_Spike_SCE.Rds")
cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "cellmix3 Done! save the normalized count to file.\n"), file = log_file, append = TRUE)
```



```{r}
sce_SC4_qc <- sce_SC4_qc[order(isSpike(sce_SC4_qc)),]
SpikeInfo = data.frame(ERCCID=cms_095046$ERCC.ID, count=cms_095046$concentration.in.Mix.1..attomoles.ul.)
SpikeInfo = SpikeInfo[SpikeInfo$ERCCID %in% rownames(sce_SC4_qc)[isSpike(sce_SC4_qc)],]
rownames(SpikeInfo) = SpikeInfo$ERCCID
SpikeInfo[,2] = SpikeInfo[,2]/(166.0541*3)
metadata(sce_SC4_qc) <- list(SpikeInput = SpikeInfo[rownames(sce_SC4_qc)[isSpike(sce_SC4_qc)],2])

cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "start MCMC.\n"), file = log_file, append = TRUE)
tp = system.time({
ChainNoSpikes <- BASiCS_MCMC(Data = sce_SC4_qc, N = 5000, 
                             Thin = 10, Burn = 500, 
                             WithSpikes = TRUE,Regression = TRUE,
                             PrintProgress = FALSE,
                             StoreChains=TRUE,
                             RunName="cellmix4_BASiCS_spike")
})
cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "MCMC finished.\n"), file = log_file, append = TRUE)

DenoisedCounts <- BASiCS_DenoisedCounts(Data = sce_SC4_qc, Chain = ChainNoSpikes)
logcounts(sce_SC4_qc) = log2(DenoisedCounts+1)
metadata(sce_SC4_qc)$running_time = data.frame(method=method_name,method_type=method_type,time=unname(tp)[1])

saveRDS(sce_SC4_qc,file="cellmix4_BASiCS_Spike_SCE.Rds")
cat(paste(format(Sys.time(), "%a %b %d %X %Y"), "cellmix4 Done! save the normalized count to file.\n"), file = log_file, append = TRUE)
```



