---
title: "get all running time"
output: html_notebook
---

# normalization

```{r}
meanSil_10x <- read.csv("/Users/tian.l/Dropbox/research/benchmark/xueyi/plot/10x_meanSil.csv", stringsAsFactors = FALSE, row.names = 1)
meanSil_sc <- read.csv("/Users/tian.l/Dropbox/research/benchmark/xueyi/plot/sc_meanSil.csv", stringsAsFactors = FALSE, row.names = 1)

meanSil_mRNA <- read.csv("/Users/tian.l/Dropbox/research/benchmark/xueyi/plot/mRNA_meanSil.csv", stringsAsFactors = FALSE, row.names = 1)

meanSil_9cell3 <- read.csv("/Users/tian.l/Dropbox/research/benchmark/xueyi/plot/9cell_meanSil.csv", stringsAsFactors = FALSE, row.names = 1)
meanSil_9cell1 <- read.csv("/Users/tian.l/Dropbox/research/benchmark/xueyi/plot/9cell1_meanSil.csv", stringsAsFactors = FALSE, row.names = 1)
meanSil_9cell2 <- read.csv("/Users/tian.l/Dropbox/research/benchmark/xueyi/plot/9cell2_meanSil.csv", stringsAsFactors = FALSE, row.names = 1)
meanSil_9cell4 <- read.csv("/Users/tian.l/Dropbox/research/benchmark/xueyi/plot/9cell4_meanSil.csv", stringsAsFactors = FALSE, row.names = 1)
```

```{r}
time_norm = rbind(meanSil_10x, meanSil_sc, meanSil_mRNA, meanSil_9cell3, meanSil_9cell1, meanSil_9cell2, meanSil_9cell4)
time_norm$method[time_norm$method=="zinbwave"] = "ZINB-WaVE"
time_norm$method[grep("kNN",time_norm$method)] = "kNN"
time_norm = time_norm[!(time_norm$method=="raw count"),]

time_norm = aggregate(elapsed~method,data=time_norm,mean)
time_norm$elapsed = log10(time_norm$elapsed)
```

# clustering

```{r}
load("~/Dropbox/research/benchmark/saskia/Clustering_Results/10x_Data/Time_Taken.RData")
time_taken_10x = data.frame(method=names(time_taken),elapsed=unlist(lapply(time_taken,function(x){x[3]})))

load("~/Dropbox/research/benchmark/saskia/Clustering_Results/SC3_Data/Time_Taken.RData")
time_taken_SC3_Data = data.frame(method=names(time_taken),elapsed=unlist(lapply(time_taken,function(x){x[3]})))

load("~/Dropbox/research/benchmark/saskia/Clustering_Results/mRNAmix2_Data/Time_Taken.RData")
time_taken_mRNAmix2 = data.frame(method=names(time_taken),elapsed=unlist(lapply(time_taken,function(x){x[3]})))

load("~/Dropbox/research/benchmark/saskia/Clustering_Results/DropSeq_Data/Time_Taken.RData")
time_taken_DropSeq_Data = data.frame(method=names(time_taken),elapsed=unlist(lapply(time_taken,function(x){x[3]})))

load("~/Dropbox/research/benchmark/saskia/Clustering_Results/CelSeq_Data/Time_Taken.RData")
time_taken_CelSeq_sc = data.frame(method=names(time_taken),elapsed=unlist(lapply(time_taken,function(x){x[3]})))

load("~/Dropbox/research/benchmark/saskia/Clustering_Results/mRNAmix8_Data/Time_Taken.RData")
time_taken_mRNAmix8 = data.frame(method=names(time_taken),elapsed=unlist(lapply(time_taken,function(x){x[3]})))

time_cluster = rbind(time_taken_10x, time_taken_SC3_Data, time_taken_mRNAmix2, time_taken_DropSeq_Data, time_taken_CelSeq_sc, time_taken_mRNAmix8)

time_cluster = aggregate(elapsed~method,data=time_cluster,mean)
time_cluster$elapsed = log10(time_cluster$elapsed)
```


```{r}
traj_time_monocle.DDRTree <- read.csv("~/Dropbox/research/benchmark/traj_result/trajectory_time_monocle-DDRTree_.csv", stringsAsFactors=FALSE)
traj_time_TSCAN <- read.csv("~/Dropbox/research/benchmark/traj_result/trajectory_time_TSCAN_.csv", stringsAsFactors=FALSE)
traj_time_slingshot <- read.csv("~/Dropbox/research/benchmark/traj_result/trajectory_time_slingshot_.csv", stringsAsFactors=FALSE)
traj_time_DPT <- read.csv("~/Dropbox/research/benchmark/traj_result/trajectory_time_DPT_.csv", stringsAsFactors=FALSE)
traj_time_SLICER <- read.csv("~/Dropbox/research/benchmark/traj_result/trajectory_time_SLICER_.csv", stringsAsFactors=FALSE)

time_traj = rbind(traj_time_monocle.DDRTree, traj_time_TSCAN, traj_time_slingshot, traj_time_DPT, traj_time_SLICER)
time_traj$time_taken = log10(time_traj$time_taken/6)
colnames(time_traj) = c("method", "elapsed")
```

```{r}
time_all = rbind(time_norm, time_cluster, time_traj)
rownames(time_all) = time_all$method
```




