---
title: "summary plot"
output: html_notebook
---

```{r,warning=FALSE,message=FALSE}
library(ggplot2)
library(pheatmap)
```


```{r,warning=FALSE,message=FALSE}
load("~/Dropbox/research/benchmark/rdata/9cellmix_qc.RData")
load("~/Dropbox/research/benchmark/rdata/sincell_with_class.RData")
load("~/Dropbox/research/benchmark/rdata/mRNAmix_qc.RData")
```

# get averaged data quality for each dataset

```{r}
cnt_median = log2(c(median(sce2_qc$total_count_per_cell),
               median(sce8_qc$total_count_per_cell),
               median(sce_SC1_qc$total_count_per_cell),
               median(sce_SC2_qc$total_count_per_cell),
               median(sce_SC3_qc$total_count_per_cell),
               median(sce_SC4_qc$total_count_per_cell),
               median(sce10x_qc$total_count_per_cell),
               median(sce4_qc$total_count_per_cell),
               median(scedrop_qc_qc$total_count_per_cell)))

cnt_median[1:2] = cnt_median[1:2]-mean(cnt_median[1:2])
cnt_median[3:6] = cnt_median[3:6]-mean(cnt_median[3:6])
cnt_median[7:9] = cnt_median[7:9]-mean(cnt_median[7:9])

gene_median = log2(c(median(sce2_qc$number_of_genes),
               median(sce8_qc$number_of_genes),
               median(sce_SC1_qc$number_of_genes),
               median(sce_SC2_qc$number_of_genes),
               median(sce_SC3_qc$number_of_genes),
               median(sce_SC4_qc$number_of_genes),
               median(sce10x_qc$number_of_genes),
               median(sce4_qc$number_of_genes),
               median(scedrop_qc_qc$number_of_genes)))

gene_median[1:2] = gene_median[1:2]-mean(gene_median[1:2])
gene_median[3:6] = gene_median[3:6]-mean(gene_median[3:6])
gene_median[7:9] = gene_median[7:9]-mean(gene_median[7:9])

data_quality = scale(cnt_median)+scale(gene_median)
data_quality
```

# get population heterogeneity and biological variation

```{r}
commonDisp <- read.csv("~/Dropbox/research/benchmark/commonDisp.csv", header=T)
disp_df = data.frame(val=commonDisp[,2],
                     batch=c("RNAmix_CEL-seq2","RNAmix_Sort-seq","cellmix1",
                                                "cellmix2","cellmix3","cellmix4",
                                                "sc_10X","sc_CEL-seq2","sc_Drop-seq"),
                     cat=rep("biological variation",9))

var_df = data.frame(val=c(7,7,34,34,34,34,3,3,3),
                     batch=c("RNAmix_CEL-seq2","RNAmix_Sort-seq","cellmix1",
                                                "cellmix2","cellmix3","cellmix4",
                                                "sc_10X","sc_CEL-seq2","sc_Drop-seq"),
                     cat=rep("population heterogeneity",9))

QC_df = data.frame(val=data_quality,
                     batch=c("RNAmix_CEL-seq2","RNAmix_Sort-seq","cellmix1",
                                                "cellmix2","cellmix3","cellmix4",
                                                "sc_10X","sc_CEL-seq2","sc_Drop-seq"),
                     cat=rep("data quality",9))
```

```{r}
merged_df = rbind(disp_df, var_df, QC_df)
merged_df$design = as.factor(c(rep("RNAmix",2),rep("cellmix",4),rep("singlecell",3)))
merged_df
```

# clustering results

```{r}
clustering_comparison_results <- read.csv("~/Dropbox/research/benchmark/clustering_res/clustering_comparison_results.csv", row.names=1, stringsAsFactors=FALSE)
head(clustering_comparison_results)
```


```{r}
x1 = merged_df$val[merged_df$cat=="biological variation"]
x2 = merged_df$val[merged_df$cat=="population heterogeneity"]
x3 = merged_df$val[merged_df$cat=="data quality"]
get_contri_var = function(x){
  y = clustering_comparison_results[clustering_comparison_results$method==x,"ARI"]
  c(mean(clustering_comparison_results[clustering_comparison_results$method
                                         ==x,"ARI"]),anova(lm(y~x1+x2+x3))$"Sum Sq"[1:3])
}

method_list = c("RaceID","RaceID2","RCA","sc3","Seurat")
res_cluster = Reduce(rbind, lapply(method_list,get_contri_var))
rownames(res_cluster) = method_list
colnames(res_cluster) = c("overall performance","biological variation", "population heterogeneity", "data quality")
scale(res_cluster)
```

# trajectory results

```{r}
method_list = c("SlICER", "DPT", "slingshot","TSCAN","monocle-DDRTree")
trajectory_result_list = lapply(method_list,function(x){read.csv(paste0("~/Dropbox/research/benchmark/traj_result/trajectory_result_",x,".csv"), stringsAsFactors=FALSE)})

trajectory_result = Reduce(rbind,trajectory_result_list)


trajectory_result$bcv = NA
trajectory_result$bio_h = NA
trajectory_result$QC = NA
trajectory_result = rbind(trajectory_result,c(NA,NA,"TSCAN","cellmix","cellmix2"))
trajectory_result = rbind(trajectory_result,c(NA,NA,"TSCAN","cellmix","cellmix3"))
trajectory_result = rbind(trajectory_result,c(NA,NA,"TSCAN","cellmix","cellmix4"))

merged_df_traj = merged_df
merged_df_traj$val[merged_df_traj$val==34] = 10   # we only used 10 clusters in trajectory analysis
for(da in c("cellmix1", "cellmix2", "cellmix3", "cellmix4", "RNAmix_CEL-seq2", "RNAmix_Sort-seq")){
  trajectory_result[trajectory_result$dataset==da,"bcv"] = merged_df_traj[merged_df_traj$batch==da & merged_df_traj$cat=="biological variation","val"]
  trajectory_result$bio_h[trajectory_result$dataset==da] = merged_df_traj[merged_df_traj$batch==da & merged_df_traj$cat=="population heterogeneity","val"]
  trajectory_result$QC[trajectory_result$dataset==da] = merged_df_traj[merged_df_traj$batch==da & merged_df_traj$cat=="data quality","val"]
}

trajectory_result$QC = as.numeric(trajectory_result$QC)
trajectory_result$bio_h = as.numeric(trajectory_result$bio_h)
trajectory_result$bcv = as.numeric(trajectory_result$bcv)
trajectory_result$corr = as.numeric(trajectory_result$corr)



anova(lm(corr~bcv+bio_h+QC,data=trajectory_result[trajectory_result$method=="SLICER",]))#$"Sum Sq"[1:3]


method_list =unique(trajectory_result$method)
res_trajectory = Reduce(rbind, lapply(method_list,function(x){y=trajectory_result[trajectory_result$method==x,"corr"];c(mean(trajectory_result[trajectory_result$method==x,]$corr,na.rm = T),anova(lm(corr~bcv+bio_h+QC,data=trajectory_result[trajectory_result$method==x,],na.action=na.omit))$"Sum Sq"[1:3])}))

rownames(res_trajectory) = method_list
colnames(res_trajectory) = c("overall performance","biological variation", "population heterogeneity", "data quality")
scale(res_trajectory)
```

```{r}
res_all = rbind(scale(res_cluster),scale(res_trajectory))
```

```{r}
pheatmap(res_all,cluster_rows = F,cluster_cols = F,gaps_row = c(nrow(res_cluster)),gaps_col = c(1))
```


```{r}
tenx_sil_all <- read.csv("~/Dropbox/research/benchmark/xueyi/plot/10x_sil_all.csv", row.names=1, stringsAsFactors=FALSE)
sc_sil_all <- read.csv("~/Dropbox/research/benchmark/xueyi/plot/sc_sil_all.csv", row.names=1, stringsAsFactors=FALSE)

cellmix3_sil_all <- read.csv("~/Dropbox/research/benchmark/xueyi/plot/9cell_sil_all.csv", row.names=1, stringsAsFactors=FALSE)
cellmix1_sil_all <- read.csv("~/Dropbox/research/benchmark/xueyi/plot/9cell1_sil_all.csv", row.names=1, stringsAsFactors=FALSE)
cellmix2_sil_all <- read.csv("~/Dropbox/research/benchmark/xueyi/plot/9cell2_sil_all.csv", row.names=1, stringsAsFactors=FALSE)
cellmix4_sil_all <- read.csv("~/Dropbox/research/benchmark/xueyi/plot/9cell4_sil_all.csv", row.names=1, stringsAsFactors=FALSE)

mRNA_sil_all <- read.csv("~/Dropbox/research/benchmark/xueyi/plot/mRNA_sil_all.csv", row.names=1, stringsAsFactors=FALSE)
```


```{r}
tenx_sil_all$bcv = merged_df[merged_df$batch=="sc_10X" & merged_df$cat=="biological variation","val"]
tenx_sil_all$bio_h = merged_df[merged_df$batch=="sc_10X" & merged_df$cat=="population heterogeneity","val"]
tenx_sil_all$QC = merged_df[merged_df$batch=="sc_10X" & merged_df$cat=="data quality","val"]

sc_sil_all$bcv = merged_df[merged_df$batch=="sc_CEL-seq2" & merged_df$cat=="biological variation","val"]
sc_sil_all$bio_h = merged_df[merged_df$batch=="sc_CEL-seq2" & merged_df$cat=="population heterogeneity","val"]
sc_sil_all$QC = merged_df[merged_df$batch=="sc_CEL-seq2" & merged_df$cat=="data quality","val"]

mRNA_sil_all$bcv = merged_df[merged_df$batch=="RNAmix_CEL-seq2" & merged_df$cat=="biological variation","val"]
mRNA_sil_all$bio_h = merged_df[merged_df$batch=="RNAmix_CEL-seq2" & merged_df$cat=="population heterogeneity","val"]
mRNA_sil_all$QC = merged_df[merged_df$batch=="RNAmix_CEL-seq2" & merged_df$cat=="data quality","val"]

cellmix1_sil_all$bcv = merged_df[merged_df$batch=="cellmix1" & merged_df$cat=="biological variation","val"]
cellmix1_sil_all$bio_h = merged_df[merged_df$batch=="cellmix1" & merged_df$cat=="population heterogeneity","val"]
cellmix1_sil_all$QC = merged_df[merged_df$batch=="cellmix1" & merged_df$cat=="data quality","val"]

cellmix2_sil_all$bcv = merged_df[merged_df$batch=="cellmix2" & merged_df$cat=="biological variation","val"]
cellmix2_sil_all$bio_h = merged_df[merged_df$batch=="cellmix2" & merged_df$cat=="population heterogeneity","val"]
cellmix2_sil_all$QC = merged_df[merged_df$batch=="cellmix2" & merged_df$cat=="data quality","val"]

cellmix3_sil_all$bcv = merged_df[merged_df$batch=="cellmix3" & merged_df$cat=="biological variation","val"]
cellmix3_sil_all$bio_h = merged_df[merged_df$batch=="cellmix3" & merged_df$cat=="population heterogeneity","val"]
cellmix3_sil_all$QC = merged_df[merged_df$batch=="cellmix3" & merged_df$cat=="data quality","val"]

cellmix4_sil_all$bcv = merged_df[merged_df$batch=="cellmix4" & merged_df$cat=="biological variation","val"]
cellmix4_sil_all$bio_h = merged_df[merged_df$batch=="cellmix4" & merged_df$cat=="population heterogeneity","val"]
cellmix4_sil_all$QC = merged_df[merged_df$batch=="cellmix4" & merged_df$cat=="data quality","val"]
```


```{r}
sil_all = rbind(tenx_sil_all,sc_sil_all,mRNA_sil_all,cellmix1_sil_all,cellmix2_sil_all,cellmix3_sil_all,cellmix4_sil_all)
sil_all$method <- sub("zinbwave", "ZINB-WaVE", sil_all$method)
sil_all$method <- sub("zinbwave W", "ZINB-WaVE W", sil_all$method)

method_list =unique(sil_all$method)

method_list = method_list[!(method_list %in% c("CPM_DrImpute","kNN (k=31)","kNN (k=63)","raw count","ZINB-WaVE W"))]

res_norm = Reduce(rbind, lapply(method_list,function(x){y=sil_all[sil_all$method==x,"sil_width"];c(mean(sil_all[sil_all$method==x,]$sil_width,na.rm = T),anova(lm(sil_width~bcv+bio_h+QC,data=sil_all[sil_all$method==x,],na.action=na.omit))$"Sum Sq"[1:3])}))
rownames(res_norm) = method_list
colnames(res_norm) = c("overall performance","biological variation", "population heterogeneity", "data quality")
res_norm = res_norm[!(rownames(res_norm)=="SCnorm"),]
rownames(res_norm)[rownames(res_norm)=="kNN (k=15)"]="kNN"

scale(res_norm)
```


```{r}
res_norm = res_norm[order(res_norm[,1],decreasing = T),]
res_cluster = res_cluster[order(res_cluster[,1],decreasing = T),]
res_trajectory = res_trajectory[order(res_trajectory[,1],decreasing = T),]

res_all = rbind(scale(res_norm),scale(res_cluster),scale(res_trajectory))

res_all = as.data.frame(res_all)
res_all$time = time_all[rownames(res_all),"elapsed"]

range01 <- function(x){(x-min(x))/(max(x)-min(x))}

res_all = apply(res_all, 2, range01)
```

```{r}
pdf("summary_plot.pdf")
pheatmap(res_all,cluster_rows = F,cluster_cols = F,gaps_row = c(nrow(res_norm),nrow(res_norm)+nrow(res_cluster)),gaps_col = c(1,4),
         fontsize=15,legend=F)
dev.off()
```


```{r}
pheatmap(res_all,cluster_rows = F,cluster_cols = F,gaps_row = c(nrow(res_norm),nrow(res_norm)+nrow(res_cluster)),gaps_col = c(1,4))
```





